# Generated by Django 2.2.17 on 2021-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_retro_toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo5'),
        ),
    ]
