# Generated by Django 2.2.17 on 2022-05-13 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find_retro_toys', '0003_auto_20211021_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_retro_toys.MessageRoom', verbose_name='Message_room_id'),
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageroom_post', to='find_retro_toys.Post', verbose_name='MessageRoom Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_retro_toys.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
