# Generated by Django 2.2.17 on 2022-06-16 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_retro_toys', '0004_auto_20220513_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_numbers',
            field=models.IntegerField(blank=True, null=True, verbose_name='like_numbers'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='find_retro_toys.Post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
