# Generated by Django 2.2.17 on 2022-06-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_retro_toys', '0005_auto_20220616_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_numbers',
        ),
    ]
