# Generated by Django 2.2.17 on 2022-06-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_retro_toys', '0006_remove_post_like_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_numbers',
            field=models.IntegerField(default=0),
        ),
    ]
